packages:
  # all packages in direct subdirs of packages/
  - "packages/contracts"
  # all packages in subdirs of components/
  - "src"
  # exclude packages that are inside test directories
  - "!**/test/**"
